const URLPARAMETERS = {
  depth: 2,
  limit: 250,
  fruchtermann: "fruchtermann",
  nodeColorByCollection: false,
  edgeColorByCollection: false,
  nodeColor: "fbe08e",
  //nodeColor: "dee072",
  //nodeColor: "ff0000",
  nodeColorAttribute: "",
  edgeColor: "848484",
  //edgeColor: "555555",
  edgeColorAttribute: "",
  nodeLabel: "",
  edgeLabel: "",
  edgeType: "line",
  nodeSize: "",
  nodeSizeByEdges: false,
  edgeEditable: true,
  nodeLabelByCollection: false,
  edgeLabelByCollection: false,
  nodeStart: "",
  barnesHutOptimize: false,
  query: "",
  //mode: "all",
};

//nodeLabel: "_key",
//edgeLabel: "_id",

export default URLPARAMETERS;
