{
 "title": "IResearch",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Size", "label": "Dataset size", "query": "1000000,  10000000, 33332620" }
  ]
 },
 "panels": [
  {
   "title": "HighPhrase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{engine=\"IResearch\",category=\"HighPhrase\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"}) + avg(Time{engine=\"IResearch\",category=\"HighPhrase\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Building\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{engine=\"Lucene\",category=\"HighPhrase\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "HighTerm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"HighTerm\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) + avg(Time{category=\"HighTerm\",stage=\"Building\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) ",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{engine=\"Lucene\",category=\"HighTerm\", size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "MedPhrase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"MedPhrase\",stage=\"Executing\"}) + avg(Time{engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"MedPhrase\",stage=\"Building\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"MedPhrase\",stage=\"Executing\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "MedTerm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"MedTerm\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"MedTerm\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "LowPhrase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"LowPhrase\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) + avg(Time{category=\"LowPhrase\",stage=\"Building\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) ",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"LowPhrase\",stage=\"Executing\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) ",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "LowTerm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"LowTerm\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"LowTerm\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "AndHighHigh",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{engine=\"IResearch\",category=\"AndHighHigh\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"}) + avg(Time{engine=\"IResearch\",category=\"AndHighHigh\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Building\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{engine=\"Lucene\",category=\"AndHighHigh\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"}) ",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "OrHighHigh",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"OrHighHigh\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) + avg(Time{category=\"OrHighHigh\",stage=\"Building\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) ",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"OrHighHigh\",stage=\"Executing\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "OrHighLow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"OrHighLow\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) + avg(Time{category=\"OrHighLow\",stage=\"Building\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"OrHighLow\",stage=\"Executing\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) ",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "OrHighMed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"OrHighMed\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) + avg(Time{category=\"OrHighMed\",stage=\"Building\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"OrHighMed\",stage=\"Executing\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "AndHighLow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{engine=\"IResearch\",category=\"AndHighLow\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"}) + avg(Time{engine=\"IResearch\",category=\"AndHighLow\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Building\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{engine=\"Lucene\",category=\"AndHighLow\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "AndHighMed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{engine=\"IResearch\",category=\"AndHighMed\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"}) + avg(Time{engine=\"IResearch\",category=\"AndHighMed\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Building\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{engine=\"Lucene\",category=\"AndHighMed\",size=\"$Size\",platform=\"Linux\",branch=\"master\", stage=\"Executing\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "Wildcard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"Wildcard\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) + avg(Time{category=\"Wildcard\",stage=\"Building\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"Wildcard\",stage=\"Executing\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) ",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "Prefix3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Time{category=\"Prefix3\",stage=\"Executing\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"}) + avg(Time{category=\"Prefix3\",stage=\"Building\",engine=\"IResearch\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Time{category=\"Prefix3\",stage=\"Executing\",engine=\"Lucene\",size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "Minor (reclaiming a frame) page faults (Index)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(MinorPageFaults{engine=\"IResearch\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Index\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(MinorPageFaults{engine=\"Lucene\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Index\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "Minor (reclaiming a frame) page faults (Query)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(MinorPageFaults{engine=\"IResearch\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Query\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(MinorPageFaults{engine=\"Lucene\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Query\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "Index creation time (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Wall_Clock{category=\"Index\",engine=\"IResearch\", size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "IResearch"
    },
    {
     "expr": "avg(Wall_Clock{category=\"Index\",engine=\"Lucene\", size=\"$Size\",platform=\"Linux\",branch=\"master\"})",
     "legendFormat": "Lucene"
    }
   ]
  },
  {
   "title": "Maximum resident set size (kbytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Memory{engine=\"IResearch\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Index\"})",
     "legendFormat": "IResearch-Index"
    },
    {
     "expr": "avg(Memory{engine=\"Lucene\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Index\"})",
     "legendFormat": "Lucene-Index"
    },
    {
     "expr": "avg(Memory{engine=\"IResearch\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Query\"})",
     "legendFormat": "IResearch-Query"
    },
    {
     "expr": "avg(Memory{engine=\"Lucene\", size=\"$Size\",platform=\"Linux\",branch=\"master\",category=\"Query\"})",
     "legendFormat": "Lucene-Query"
    }
   ]
  }
 ]
}