#!/usr/bin/env bash
adb_path="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
ent_dir="enterprise"

echo "ArangoDB directory: $adb_path"
echo "Enterprise directory: $adb_path/$ent_dir"

cd "$adb_path"
community_diff=$(git diff HEAD --diff-filter=ACMR --name-only -- '*.cpp' '*.hpp' '*.cc' '*.c' '*.h')

if [ -d "$adb_path/$ent_dir" ] # assume enterprise directory is within arangodb directory
then
   cd "$adb_path/$ent_dir"
   enterprise_diff=$(git diff HEAD --diff-filter=ACMR --name-only -- '*.cpp' '*.hpp' '*.cc' '*.c' '*.h' | sed "s,^,$ent_dir/,")
fi

diff="$community_diff $enterprise_diff"
if ! [[ -z "${diff// }" ]]; then
  docker run --rm -v "$adb_path":/usr/src/arangodb clang-format:latest "$diff"
fi

echo "(done)"