#!/usr/bin/env bash
adb_path="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

echo "ArangoDB directory: $adb_path"
cd "$adb_path"

community_diff=$(git diff HEAD --diff-filter=ACMR --name-only -- '*.cpp' '*.hpp' '*.cc' '*.c' '*.h')
if ! [[ -z "${community_diff// }" ]]; then
  docker run --rm -v "$adb_path":/usr/src/arangodb clang-format:latest "$community_diff"
fi

echo "(done)"