#!/usr/bin/env bash
# Configure this hook by running the following:
#    1. cd arangodb
#    2. cp .githooks/pre-commit-macos .git/hooks/pre-commit
#    3. git config core.hooksPath .git/hooks
# pre-requisite: Docker
# pre-requisite: Git 2.9+

adb_path="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/../.." &> /dev/null && pwd )"

echo "ArangoDB directory: $adb_path"
cd "$adb_path"

# some .h files are currently misinterpreted as Objective-C files by clang-format
# TODO: rename .h files to .hpp, and remove .h file ending from the grep here
community_diff=$(git diff HEAD --diff-filter=ACMRT --name-only -- arangod/ client-tools/ lib/ tests/ | grep -e '\.ipp$' -e '\.tpp$' -e '\.cpp$' -e '\.hpp$' -e '\.cc$' -e '\.c$' -e '\.h$')
if ! [[ -z "${community_diff// }" ]]; then
  docker run --rm -u "$(id -u):$(id -g)" --mount type=bind,source="$adb_path",target=/usr/src/arangodb arangodb/clang-format:1.0 "$community_diff"
fi

echo "(done)"
