//  -*- mode: groovy-mode

def binaries = 'build/**,etc/**,Installation/Pipeline/**,js/**,scripts/**,tests/**,UnitTests/**,utils/**'
def enterpriseRepo = 'https://github.com/arangodb/enterprise'
def credentialsId = '8d893d23-6714-4f35-a239-c847c798e080'

def PowerShell(psCmd) {
    bat "powershell.exe -NonInteractive -ExecutionPolicy Bypass -Command \"\$ErrorActionPreference='Stop';[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;$psCmd;EXIT \$global:LastExitCode\""
}


node('master') {
    retry(3) {
        try {
            checkout scm
        }
        catch (err) {
            echo "GITHUB checkout failed, retrying in 5min"
            sleep 300
        }
    }
}


/*
pipeline {
    agent any 

    stages {
        stage('Checkout') {
            steps { 
                node('master') {
                    script {
                        retry(3) {
                            try {
                                checkout scm
                            }
                            catch (err) {
                                echo "GITHUB checkout failed, retrying in 5min"
                                sleep 300
                            }
                        }
                    }

                    script {
                        try {
                            echo "Trying enterprise branch ${env.BRANCH_NAME}"

                            checkout(
                                changelog: false,
                                poll: false,
                                scm: [
                                    $class: 'GitSCM',
                                    branches: [[name: "*/${env.BRANCH_NAME}"]],
                                    doGenerateSubmoduleConfigurations: false,
                                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'enterprise']],
                                    submoduleCfg: [],
                                    userRemoteConfigs: [[credentialsId: credentialsId, url: enterpriseRepo]]])
                        }
                        catch (err) {
                            echo "Failed ${env.BRANCH_NAME}, trying enterprise branch devel"

                            checkout(
                                changelog: false,
                                poll: false,
                                scm: [
                                    $class: 'GitSCM',
                                    branches: [[name: "*/devel"]],
                                    doGenerateSubmoduleConfigurations: false,
                                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'enterprise']],
                                    submoduleCfg: [],
                                    userRemoteConfigs: [[credentialsId: credentialsId, url: enterpriseRepo]]])
                        }
                    }

                    sh 'rm -rf build build-jenkins'

                    stash includes: '**', name: 'source'
                }
            }
        }

        stage('Build & Test') { 
            steps { 
                parallel(
                    'linux': {
                        node('linux') {
                            unstash 'source'
                            sh './Installation/Pipeline/build_enterprise_linux.sh 16'
                            stash includes: binaries, name: 'build-cc-lx'
                        }

                        parallel(
                            'community': {
                                node('linux') {
                                    sh './Installation/Pipeline/test_community_linux.sh 8'
                                }
                            },
                            'enterprise': {
                                node('linux') {
                                    sh './Installation/Pipeline/test_enterprise_linux.sh 8'
                                }
                            }
                        )
                    },

                    'mac': {
                        node('mac') {
                            unstash 'source'
                            sh './Installation/Pipeline/build_ee_mc.sh 16'
                            sh './Installation/Pipeline/test_ss_mm_cc_lx.sh 8'
                        }
                    },

                    'windows': {
                        node('windows') {
                            unstash 'source'
                            PowerShell(". .\\Installation\\Pipeline\\build_ee_wi.ps1")
                        }
                    }
                )
            }
        }

        stage('JS Lint') {
            steps {
                node('linux') {
                    unstash 'build-cc-lx'

                    script {
                        try {
                            sh './Installation/Pipeline/jslint.sh'
                        }
                        catch (exc) {
                            currentBuild.result = 'UNSTABLE'
                        }
                    }
                }
            }
        }
    }
}
*/
