language: minimal
dist: trusty
matrix:
  include:
    - language: c
      compiler: gcc
      env: c_tests=y cc_append=' -std=c90 -Wdeclaration-after-statement -Werror'
    - language: c
      compiler: clang
      env: c_tests=y cc_append=' -std=c90 -Wdeclaration-after-statement -Werror'
    - language: java
      env: JAVA=java JAVAC=javac
    - language: go
      go: "1.8"
      env: GO=go
    - language: go
      dist: bionic
      go: "1.12"
      env: GO=go
    - language: node_js
      node_js: "node"
      env: NODE=node
    - language: rust
      rust:
        - stable
        - beta
      dist: bionic
      env: RUST=rust
    - language: csharp
      env: MCS=mcs
    - name: Pascal
      env: FPC=fpc
      dist: bionic
      addons:
        apt:
          packages:
            - fpc
    # The pure Python versions run slowly so we need to thin the testdata
    # for languages such as Arabic where there's a lot, or else the build
    # hits the travis time limit.  With pypy, it's enough faster than we
    # can run the full tests.
    - language: python
      python: "3.7"
      env: PYTHON=python THIN_FACTOR=10
      dist: xenial
    - language: python
      python: "3.6"
      env: PYTHON=python THIN_FACTOR=10
    - language: python
      python: "3.4"
      env: PYTHON=python THIN_FACTOR=10
    - language: python
      python: "2.7"
      env: PYTHON=python THIN_FACTOR=10
    - language: python
      python: "2.6"
      env: PYTHON=python THIN_FACTOR=10
    - language: python
      python: "pypy"
      env: PYTHON=python
    - language: python
      python: "pypy3.5"
      env: PYTHON=python
before_install:
  # Try to check out a branch of the same name from the snowball-data repo
  # sibling of this snowball repo, so that PRs requiring changes to both can be
  # CI tested easily.
  #
  # If that fails, just use the standard snowball-data repo's default branch.
  - GH_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - GH_REPO_SLUG=${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}
  - GH_REPO_URL=https://github.com/${GH_REPO_SLUG%%/*}/snowball-data.git
  - echo "Trying branch $GH_BRANCH from $GH_REPO_URL"
  - git clone --depth=1 -b "$GH_BRANCH" "$GH_REPO_URL" || git clone --depth=1 https://github.com/snowballstem/snowball-data.git
script:
  - make CC="${CC:-gcc}$cc_append"
  - test -z "$c_tests" || make check CC="${CC:-gcc}$cc_append" STEMMING_DATA=snowball-data
  - test -z "$PYTHON" || make check_python python="$PYTHON" STEMMING_DATA=snowball-data
  - test -z "$JAVA" -o -z "$JAVAC" || make check_java STEMMING_DATA=snowball-data
  - test -z "$MCS" || make check_csharp MCS="$MCS" STEMMING_DATA=snowball-data
  - test -z "$NODE" || make check_js STEMMING_DATA=snowball-data
  - test -z "$RUST" || make check_rust STEMMING_DATA=snowball-data
  - test -z "$RUST" || make check_rust cargoflags=--release STEMMING_DATA=snowball-data
  - test -z "$GO" || make check_go STEMMING_DATA=snowball-data
  - test -z "$FPC" || make check_pascal STEMMING_DATA=snowball-data
