# -*- mode: Makefile; -*-

################################################################################
## LIBEV
################################################################################

BUILT_SOURCES += @LIBEV_LIBS@

@LIBEV_LIBS@:
	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILDING LIBEV"
	@echo "--------------------------------------------------------------------------------"
	@echo

	cd @top_srcdir@/3rdParty/libev && ./configure --disable-shared
	cd @top_srcdir@/3rdParty/libev && make

	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILD LIBEV FINISHED"
	@echo "--------------------------------------------------------------------------------"
	@echo

################################################################################
## V8
################################################################################

if ENABLE_64BIT
V8_BUILD_VERSION=x64.release
endif

if ENABLE_32BIT
V8_BUILD_VERSION=ia32.release
endif

BUILT_SOURCES += $(V8_LIBS)

$(V8_LIBS):
	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILDING V8"
	@echo "--------------------------------------------------------------------------------"
	@echo

if ENABLE_DARWIN
	cd @top_srcdir@/3rdParty/V8 && scons snapshot=off library=static mode=release arch=x64
else
	cd @top_srcdir@/3rdParty/V8 && make library=static snapshot=off $(V8_BUILD_VERSION)
endif

	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILD V8 FINISHED"
	@echo "--------------------------------------------------------------------------------"
	@echo
