# -*- mode: Makefile; -*-

################################################################################
## LIBEV
################################################################################

if ENABLE_64BIT
LIBEV_BUILD_VERSION=ARCH.x64
endif

if ENABLE_32BIT
LIBEV_BUILD_VERSION=ARCH.ia32
endif

if ENABLE_FORCE_32BIT
LIBEV_CFLAGS_32=-m32 -O2 -g
LIBEV_LDFLAGS_32=-m32
else
LIBEV_CFLAGS_32=-O2 -g
LIBEV_LDFLAGS_32=
endif

BUILT_SOURCES += @LIBEV_LIBS@

@LIBEV_LIBS@: .libev-build

.libev-build:
	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILDING LIBEV"
	@echo "--------------------------------------------------------------------------------"
	@echo

	mkdir @top_srcdir@/3rdParty/libev/$(LIBEV_BUILD_VERSION) || true
	cd @top_srcdir@/3rdParty/libev/$(LIBEV_BUILD_VERSION) && CFLAGS="$(LIBEV_CFLAGS_32)" orig_CFLAGS="$(LIBEV_CFLAGS_32)" LDFLAGS="$(LIBEV_LDFLAGS_32)" ../configure --disable-shared
	cd @top_srcdir@/3rdParty/libev/$(LIBEV_BUILD_VERSION) && make

	touch .libev-build

	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILD LIBEV FINISHED"
	@echo "--------------------------------------------------------------------------------"
	@echo

################################################################################
## V8
################################################################################

BUILT_SOURCES += @V8_LIBS@

@V8_LIBS@: .v8-build

.v8-build:
	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILDING V8"
	@echo "--------------------------------------------------------------------------------"
	@echo

	cd @top_srcdir@/3rdParty/V8 && make library=static snapshot=off @V8_TARGET@

	touch .v8-build

	@echo
	@echo "--------------------------------------------------------------------------------"
	@echo "BUILD V8 FINISHED"
	@echo "--------------------------------------------------------------------------------"
	@echo
