# -*- mode: Makefile; -*-

## -----------------------------------------------------------------------------
## --SECTION--                                                        JAVASCRIPT
## -----------------------------------------------------------------------------

################################################################################
### @brief JavaScript source code as header
################################################################################

JAVASCRIPT_HEADER = \
	js/common/bootstrap/js-errors.h \
	js/common/bootstrap/js-modules.h \
	js/common/bootstrap/js-print.h \
	js/client/js-client.h \
	js/server/js-server.h \
	js/server/js-ahuacatl.h

BUILT_SOURCES += $(JAVASCRIPT_HEADER)

################################################################################
### @brief JavaScript modules for browser
################################################################################

JAVASCRIPT_BROWSER = \
	html/admin/js/modules/simple-query-basics.js \
	html/admin/js/modules/simple-query.js

BUILT_SOURCES += $(JAVASCRIPT_BROWSER)

## -----------------------------------------------------------------------------
## --SECTION--                                                             MRUBY
## -----------------------------------------------------------------------------

################################################################################
### @brief MRuby source code as header
################################################################################

MRUBY_HEADER = \
	mr/common/bootstrap/mr-error.h \
	mr/server/mr-server.h

BUILT_SOURCES += $(MRUBY_HEADER)

## -----------------------------------------------------------------------------
## --SECTION--                                                     DOCUMENTATION
## -----------------------------------------------------------------------------

################################################################################
### @brief JavaScript files
################################################################################

DOXYGEN = \
	Documentation/js/actions/system/api-collection.c \
	Documentation/js/actions/system/api-cursor.c \
	Documentation/js/actions/system/api-edges.c \
	Documentation/js/actions/system/api-explain.c \
	Documentation/js/actions/system/api-index.c \
	Documentation/js/actions/system/api-query.c \
	Documentation/js/actions/system/api-simple.c \
	Documentation/js/actions/system/api-system.c \
	Documentation/js/common/bootstrap/modules.c \
	Documentation/js/common/bootstrap/print.c \
	Documentation/js/common/modules/graph.c \
	Documentation/js/common/modules/jsunity.c \
	Documentation/js/common/modules/simple-query-basics.c \
	Documentation/js/server/modules/actions.c \
	Documentation/js/server/modules/simple-query.c \
	Documentation/js/server/server.c

################################################################################
### @brief wiki pages
################################################################################

WIKI = \
	ArangoErrors \
	CommandLine \
	Compiling \
	DbaManual \
	DbaManualBasics \
	DbaManualAuthentication \
	DbaManualDatafileDebugger \
	DefineAction \
	ExamplesSetup \
	FirstStepsArangoDB \
	Glossary \
	Graphs \
	Home \
	HttpCollection \
	HttpCursor \
	HttpImport \
	HttpIndex \
	HttpInterface \
	HttpQueries \
	HttpSimple \
	HttpSystem \
	ImplementorManual \
	ImpManual \
	ImpManualBasics \
	IndexCap \
	IndexCapHttp \
	IndexGeo \
	IndexGeoHttp \
	IndexHash \
	IndexHashHttp \
	IndexSkiplist \
	IndexSkiplistHttp \
	InstallManual \
	Installing \
	JSModuleActions \
	JSModuleConsole \
	JSModuleFs \
	JSModuleGraph \
	JSModuleInternal \
	JSModules \
	Key-Value \
	RefManual \
	RestDocument \
	RestEdge \
	RestSystem \
	ShellCollection \
	ShellDocument \
	ShellEdge \
	ShellIndex \
	SimpleQueries \
	UserManual \
	UserManualBasics \
	UserManualArangosh \
        Aql \
        AqlExamples \
	jsUnity

## -----------------------------------------------------------------------------
## --SECTION--                                                       END-OF-FILE
## -----------------------------------------------------------------------------

## Local Variables:
## mode: outline-minor
## outline-regexp: "^\\(### @brief\\|## --SECTION--\\|# -\\*- \\)"
## End:
