#!/bin/sh
update-rc.d arangodb defaults
if which invoke-rc.d >/dev/null 2>&1; then
  invoke-rc.d arangodb start
else
  /etc/init.d/arangodb start
fi

echo "
ArangoDB 2 (http://www.arangodb.org)
  A multi-purpose open-source database with a flexible data model for documents,
  graphs, and key-values.

First Steps with ArangoDB:
  http:/www.arangodb.org/quickstart

Upgrading ArangoDB:
  http://www.arangodb.org/manuals/current/Upgrading.html

Upgrading ArangoDB database files:
  > /etc/init.d/arangodb upgrade

Configuration file:
  /etc/arangodb/arangod.conf

Start ArangoDB shell client:
  > /usr/bin/arangosh

Start ArangoDB service:
  > /etc/init.d/arangodb start
"
