#!/bin/sh

if [ purge = "$1" ]; then
        update-rc.d arangodb3 remove >/dev/null

	rm -rf /usr/share/arangodb3/js/apps
	rm -rf /var/log/arangodb3
	rm -rf /var/lib/arangodb3
	rm -rf /var/lib/arangodb3-apps 
fi
