env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-2-release-amd64
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg upgrade -y
    - pkg install -y autoconf gmake
  script:
    - autoconf
    #- ./configure ${COMPILER_FLAGS:+       CC="$CC $COMPILER_FLAGS"       CXX="$CXX $COMPILER_FLAGS" }       $CONFIGURE_FLAGS
    # We don't perfectly track freebsd stdlib.h definitions.  This is fine when
    # we count as a system header, but breaks otherwise, like during these
    # tests.
    - ./configure --with-jemalloc-prefix=ci_
    - export JFLAG=`sysctl -n kern.smp.cpus`
    - gmake -j${JFLAG}
    - gmake -j${JFLAG} tests
    - gmake check
