.TH arango-dfdb 8 "So 30. Sep 01:36:14 CEST 2012" "" "ArangoDB"
.SH NAME
arango-dfdb - a datafile debugger for ArangoDB
.SH SYNOPSIS
arango-dfdb options 
.SH DESCRIPTION
The arango-dfdb binary can be used to verify the datafiles of an
ArangoDB database server. The script must be run with exclusive 
access to the server's data directory, meaning the ArangoDB 
server must not be running and accessing the datafiles in the 
specified data directory.
More specific instructions are displayed when the program is invoked.
.SH OPTIONS
.IP "--database.directory <string>"
path to the database directory 
.SH EXAMPLES
.EX
shell> arango-dfdb --database.directory /data/arangodb
starts the debugger with database directory /data/arangodb 
.EE


.SH AUTHOR
	    Copyright triAGENS GmbH, Cologne, Germany
