.TH foxx-manager 8 "3.0.x-devel" "ArangoDB" "ArangoDB"
.SH NAME
foxx-manager - a Foxx application manager for ArangoDB
.SH SYNOPSIS
foxx-manager options 
.SH DESCRIPTION
The foxx-manager binary can be used to manage Foxx applications in the
ArangoDB database server. Foxx applications can be installed and
uninstalled.
.SH OPTIONS
For a complete list of options, please refer to the ArangoDB
online manual, available at https://www.arangodb.com/

.SH AUTHOR
Copyright ArangoDB GmbH, Cologne, Germany

