.TH rcarangod 8 "So 30. Sep 01:36:14 CEST 2012" "" "ArangoDB"
.SH NAME
rcarangod - control script for the ArangoDB database server
.SH SYNOPSIS
rcarangod start|stop
.SH DESCRIPTION
The rcarangod script controls the operation of the ArangoDB
database server daemon running on the system. The rcarangod script
is normally run at system boot time with the "start" argument, and
at system shutdown time with the "stop" argument. 
It can also be invoked manually at any time to start or stop the
ArangoDB database server.
.SH SEE ALSO
.BR arangod "(8), "

.SH AUTHOR
	    Copyright triAGENS GmbH, Cologne, Germany
