version: 2.1

jobs:
  test-job:
    parameters:
      size:
        type: string
    docker:
      - image: cimg/base:current
    resource_class: << parameters.size >>
    steps:
      - run: echo "<< parameters.size >>"
      - run: cat /sys/fs/cgroup/cpu.max
      - run: cat /sys/fs/cgroup/cpu.stat
      - run: cat /sys/fs/cgroup/memory.max
      - run: nproc
      - run: cat /proc/self/status | grep Cpus_allowed_list
      - run: cat /proc/cpuinfo


workflows:
  setup:
    jobs:
      - test-job:
          name: small-x64
          size: small
      - test-job:
          name: medium-x64
          size: medium
      - test-job:
          name: medium+-x64
          size: medium+
      - test-job:
          name: large-x64
          size: large
      - test-job:
          name: xlarge-x64
          size: xlarge
      - test-job:
          name: 2xlarge-x64
          size: 2xlarge

      - test-job:
          name: medium-arm
          size: arm.medium
      - test-job:
          name: large-arm
          size: arm.large
      - test-job:
          name: xlarge-arm
          size: arm.xlarge
      - test-job:
          name: 2xlarge-arm
          size: arm.2xlarge

      - test-job:
          name: small-arango-x64
          size: arangodb/small-amd64
      - test-job:
          name: medium-arango-x64
          size: arangodb/medium-amd64
      - test-job:
          name: large-arango-x64
          size: arangodb/large-amd64
      - test-job:
          name: xlarge-arango-x64
          size: arangodb/xlarge-amd64
      - test-job:
          name: 2xlarge-arango-x64
          size: arangodb/2xlarge-amd64

      - test-job:
          name: small-arango-arm
          size: arangodb/small-arm64
      - test-job:
          name: medium-arango-arm
          size: arangodb/medium-arm64
      - test-job:
          name: large-arango-arm
          size: arangodb/large-arm64
      - test-job:
          name: xlarge-arango-arm
          size: arangodb/xlarge-arm64
      - test-job:
          name: 2xlarge-arango-arm
          size: arangodb/2xlarge-arm64
