version: 2.1

jobs:
  test-job:
    parameters:
      size:
        type: string
    docker:
      - image: arangodb/ubuntubuildarangodb-devel:20
    resource_class: << parameters.size >>
    steps:
      - run:
          command: |
            set -o xtrace
            echo "<< parameters.size >>"
            cat /sys/fs/cgroup/cpu.max
            cat /sys/fs/cgroup/cpuset.cpus.effective
            cat /sys/fs/cgroup/cpu.stat
            cat /sys/fs/cgroup/memory.max
            nproc
            cat /proc/cpuinfo | grep processor | wc -l
            echo "----"
            cat /proc/version
            cat /proc/sys/kernel/osrelease
            cat /sys/devices/system/clocksource/clocksource0/current_clocksource
            cat /sys/kernel/mm/transparent_hugepage/enabled
            taskset -pc $$
      - run:
          name: sysctrl
          command: sysctl -a
      - run:
          command: |
            set -o xtrace
            cat /proc/self/status
      - run:
          name: cpuinfo
          command: |
            set -o xtrace
            cat /proc/cpuinfo

      - run:
          name: concurrency
          command: |
            set -o xtrace
            printf '#include <iostream>\n#include <thread>\n#include <unistd.h>\nint main() { std::cout \x3c\x3c "hardware_concurrency: " \x3c\x3c std::thread::hardware_concurrency() \x3c\x3c std::endl; std::cout \x3c\x3c "sysconf(_SC_NPROCESSORS_ONLN): " \x3c\x3c sysconf(_SC_NPROCESSORS_ONLN) \x3c\x3c std::endl; }\n' > /tmp/concurrency.cpp
            g++ -std=c++20 -pthread -o /tmp/concurrency /tmp/concurrency.cpp
            /tmp/concurrency
      - run:
          name: more info
          command: |
            set -o xtrace
            set +e
            cat /sys/kernel/debug/sched/preempt
            cat /proc/sys/kernel/numa_balancing
            cat /sys/kernel/mm/transparent_hugepage/enabled
            cat /sys/kernel/mm/transparent_hugepage/defrag
            cat /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
            cat /sys/devices/system/cpu/nohz_full
            cat /sys/devices/system/cpu/isolated
            cat /sys/devices/system/cpu/smt/control
            ls /proc/sys/kernel | grep futex
            cat /proc/sys/kernel/futex_requeue_pi
            cat /sys/kernel/mm/lru_gen/enabled
            cat /proc/sys/vm/compact_memory
            cat /proc/sys/vm/compaction_proactiveness
            cat /proc/sys/vm/overcommit_memory
            cat /proc/sys/vm/overcommit_ratio
            cat /proc/sys/vm/user_reserve_kbytes
            cat /proc/sys/kernel/timer_migration
            cat /proc/sys/kernel/sched_migration_cost_ns
            cat /proc/sys/kernel/watchdog
            cat /proc/sys/kernel/watchdog_thresh
            grep PREEMPT /boot/config-$(uname -r)

workflows:
  setup:
    jobs:
      - test-job:
          name: small-x64
          size: small
      - test-job:
          name: medium-x64
          size: medium
      - test-job:
          name: medium+-x64
          size: medium+
      - test-job:
          name: large-x64
          size: large
      - test-job:
          name: xlarge-x64
          size: xlarge
      - test-job:
          name: 2xlarge-x64
          size: 2xlarge

      - test-job:
          name: medium-arm
          size: arm.medium
      - test-job:
          name: large-arm
          size: arm.large
      - test-job:
          name: xlarge-arm
          size: arm.xlarge
      - test-job:
          name: 2xlarge-arm
          size: arm.2xlarge

      - test-job:
          name: small-arango-x64
          size: arangodb/small-amd64
      - test-job:
          name: medium-arango-x64
          size: arangodb/medium-amd64
      - test-job:
          name: large-arango-x64
          size: arangodb/large-amd64
      - test-job:
          name: xlarge-arango-x64
          size: arangodb/xlarge-amd64
      - test-job:
          name: 2xlarge-arango-x64
          size: arangodb/2xlarge-amd64

      - test-job:
          name: small-arango-arm
          size: arangodb/small-arm64
      - test-job:
          name: medium-arango-arm
          size: arangodb/medium-arm64
      - test-job:
          name: large-arango-arm
          size: arangodb/large-arm64
      - test-job:
          name: xlarge-arango-arm
          size: arangodb/xlarge-arm64
      - test-job:
          name: 2xlarge-arango-arm
          size: arangodb/2xlarge-arm64
