#!/bin/sh
update-rc.d arangodb start 99 2 3 4 5 . stop 00 0 1 6 . >/dev/null
/etc/init.d/arangodb start

echo "
ArangoDB 2 (http://www.arangodb.com)
  A multi-purpose open-source database with a flexible data model for documents,
  graphs, and key-values.

First Steps with ArangoDB:
  https://docs.arangodb.com/FirstSteps/README.html

Upgrading ArangoDB:
  https://docs.arangodb.com/Installing/Upgrading.html

Upgrading ArangoDB database files:
  > /etc/init.d/arangodb upgrade

Configuration file:
  /etc/arangodb/arangod.conf

Start ArangoDB shell client:
  > /usr/bin/arangosh

Start ArangoDB service:
  > /etc/init.d/arangodb start

Remote access to the ArangoDB server is disabled for security reasons. 
In order to enable it, please change the server endpoint from '127.0.0.1' 
to '0.0.0.0' in ArangoDB's configuration file '/etc/init.d/arangod.conf'.
"
