#!/bin/sh
set -e

getent group arangodb >/dev/null || groupadd -r arangodb 
getent passwd arangodb >/dev/null || useradd -r -g arangodb -d /usr/share/arangodb3 -s /bin/false -c "ArangoDB Application User" arangodb 

install -o arangodb -g arangodb -m 755 -d /var/lib/arangodb3
install -o arangodb -g arangodb -m 755 -d /var/lib/arangodb3-apps
install -o arangodb -g arangodb -m 755 -d /var/log/arangodb3

rm -rf /usr/share/arangodb3/js.old

if test -d /usr/share/arangodb3/js; then
  mv /usr/share/arangodb3/js /usr/share/arangodb3/js.old
fi


