#!/bin/sh
set -e

# Automatically added by dh_installinit
if [ -x "/etc/init.d/arangodb3" ]; then
	invoke-rc.d arangodb3 stop || exit $?
fi
# End automatically added section

set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
        deb-systemd-invoke stop arangodb3.service >/dev/null
fi
# End automatically added section
