add_subdirectory(EnumeratePathsFilter)

target_sources(arango_aql PRIVATE
  AsyncPrefetch.cpp
  BatchMaterializeDocuments.cpp
  CollectInCluster.cpp
  DecayUnnecessarySortedGather.cpp
  DistributeFilterCalcToCluster.cpp
  DistributeInCluster.cpp
  DistributeSortToCluster.cpp
  FuseFilters.cpp
  GeoIndex.cpp
  InlineSubqueries.cpp
  InterchangeAdjacentEnumerations.cpp
  JoinIndexNodes.cpp
  MaterializeIntoSeparateVariable.cpp
  ReplaceAnyEqWithIn.cpp
  MoveCalculationsDown.cpp
  MoveCalculationsUp.cpp
  MoveFiltersIntoEnumerate.cpp
  MoveFiltersUp.cpp
  OptimizeCount.cpp
  OptimizePaths.cpp
  OptimizeProjections.cpp
  OptimizeSubqueries.cpp
  OptimizeTraversals.cpp
  OptimizerRulesGraph.cpp
  OptimizerRulesIResearchView.cpp
  OptimizerRulesIndexNode.cpp
  OptimizerRulesLateMaterializedCommon.cpp
  ParallelizeGather.cpp
  PropagateConstantAttributes.cpp
  PushDownLateMaterialization.cpp
  PushFilterIntoEnumerateNear.cpp
  PushLimitIntoIndex.cpp
  RemoveCollectVariables.cpp
  RemoveDataModificationOutVariables.cpp
  RemoveFiltersCoveredByIndex.cpp
  RemoveFiltersCoveredByTraversal.cpp
  RemoveRedundantCalculations.cpp
  RemoveRedundantOr.cpp
  RemoveRedundantSorts.cpp
  RemoveTraversalPathVariable.cpp
  RemoveUnnecessaryCalculations.cpp
  RemoveUnnecessaryFilters.cpp
  RemoveUnnecessaryRemoteScatter.cpp
  ReplaceEntriesWithObjectIteration.cpp
  ReplaceEqualAttributeAccess.cpp
  ReplaceLikeWithRange.cpp
  ReplaceNearWithinFulltext.cpp
  ReplaceOrWithIn.cpp
  RestrictToSingleShard.cpp
  ScatterInCluster.cpp
  SimplifyConditions.cpp
  SortInValues.cpp
  SortLimit.cpp
  SpecializeCollect.cpp
  SpliceSubqueries.cpp
  SubstituteClusterMultipleDocumentOperations.cpp
  SubstituteClusterSingleDocumentOperations.cpp
  UndistributeRemoveAfterEnumColl.cpp
  UseIndexForCollect.cpp
  UseIndexForSort.cpp
  UseIndexes.cpp
  UseVectorIndex.cpp
)
