export const SHARDS_DETAILS_FETCH = "SHARDS_DETAILS_FETCH";
export const SHARDS_DETAILS_UNSELECT = "SHARDS_DETAILS_UNSELECT";
export const SHARDS_DETAILS_FETCH_SUCCESS = "SHARDS_DETAILS_FETCH_SUCCESS";
export const SHARDS_OVERVIEW_FETCH = "SHARDS_OVERVIEW_FETCH";
export const SHARDS_OVERVIEW_FETCH_SUCCESS = "SHARDS_OVERVIEW_FETCH_SUCCESS";
