.TH arangosh 1 "3.0.x-devel" "ArangoDB" "ArangoDB"
.SH NAME
arangosh - the ArangoDB shell
.SH SYNOPSIS
arangosh [options]
.SH DESCRIPTION
The arangosh binary can be used to establish an interactive
client connection to the ArangoDB database. When the connection
is established, it can be used to execute actions on the server.
.SH OPTIONS
For a complete list of options, please refer to the ArangoDB
online manual, available at https://www.arangodb.com/

.SH AUTHOR
Copyright ArangoDB GmbH, Cologne, Germany

