.TH arangobench 1 "3.4.7-rc.1" "ArangoDB" "ArangoDB"
.SH NAME
arangobench - the ArangoDB benchmark and test tool
.SH SYNOPSIS
arangobench [options]
.SH DESCRIPTION
The arangob binary can be used to issue test requests to the 
ArangoDB database. It can be used for benchmarks or server function
testing. It supports parallel querying and batch requests.
.SH OPTIONS
For a complete list of options, please refer to the ArangoDB
online manual, available at https://www.arangodb.com/

.SH AUTHOR
Copyright ArangoDB GmbH, Cologne, Germany

