/*jslint indent: 2,
         nomen: true,
         maxlen: 100,
         sloppy: true,
         vars: true,
         white: true,
         plusplus: true */
/*global exports */

////////////////////////////////////////////////////////////////////////////////
/// @brief auto-generated file generated from mimetypes.dat
////////////////////////////////////////////////////////////////////////////////

exports.mimeTypes = {
  "gif": [ "image/gif", false ], 
  "jpg": [ "image/jpg", false ], 
  "png": [ "image/png", false ], 
  "tiff": [ "image/tiff", false ], 
  "ico": [ "image/x-icon", false ], 
  "css": [ "text/css", true ], 
  "js": [ "text/javascript", true ], 
  "json": [ "application/json", true ], 
  "html": [ "text/html", true ], 
  "htm": [ "text/html", true ], 
  "pdf": [ "application/pdf", false ], 
  "ps": [ "application/postscript", false ], 
  "txt": [ "text/plain", true ], 
  "text": [ "text/plain", true ], 
  "xml": [ "application/xml", true ], 
  "dtd": [ "application/xml-dtd", true ], 
  "svg": [ "image/svg+xml", true ], 
  "ttf": [ "application/x-font-ttf", false ], 
  "otf": [ "application/x-font-opentype", false ], 
  "woff": [ "application/font-woff", false ], 
  "eot": [ "application/vnd.ms-fontobject", false ], 
  "bz2": [ "application/x-bzip2", false ], 
  "gz": [ "application/x-gzip", false ], 
  "tgz": [ "application/x-tar", false ], 
  "zip": [ "application/x-compressed-zip", false ], 
  "doc": [ "application/msword", false ], 
  "docx": [ "application/vnd.openxmlformats-officedocument.wordprocessingml.document", false ], 
  "dotx": [ "application/vnd.openxmlformats-officedocument.wordprocessingml.template", false ], 
  "potx": [ "application/vnd.openxmlformats-officedocument.presentationml.template", false ], 
  "ppsx": [ "application/vnd.openxmlformats-officedocument.presentationml.slideshow", false ], 
  "ppt": [ "application/vnd.ms-powerpoint", false ], 
  "pptx": [ "application/vnd.openxmlformats-officedocument.presentationml.presentation", false ], 
  "xls": [ "application/vnd.ms-excel", false ], 
  "xlsb": [ "application/vnd.ms-excel.sheet.binary.macroEnabled.12", false ], 
  "xlsx": [ "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", false ], 
  "xltx": [ "application/vnd.openxmlformats-officedocument.spreadsheetml.template", false ], 
  "swf": [ "application/x-shockwave-flash", false ]
};

exports.extensions = {
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [ "xlsx" ], 
  "image/svg+xml": [ "svg" ], 
  "application/postscript": [ "ps" ], 
  "image/png": [ "png" ], 
  "application/x-font-ttf": [ "ttf" ], 
  "application/vnd.ms-excel.sheet.binary.macroEnabled.12": [ "xlsb" ], 
  "application/x-font-opentype": [ "otf" ], 
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [ "docx" ], 
  "application/x-bzip2": [ "bz2" ], 
  "application/json": [ "json" ], 
  "application/pdf": [ "pdf" ], 
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": [ "pptx" ], 
  "application/vnd.ms-fontobject": [ "eot" ], 
  "application/xml-dtd": [ "dtd" ], 
  "application/x-shockwave-flash": [ "swf" ], 
  "image/gif": [ "gif" ], 
  "image/jpg": [ "jpg" ], 
  "application/xml": [ "xml" ], 
  "application/vnd.ms-excel": [ "xls" ], 
  "image/tiff": [ "tiff" ], 
  "application/vnd.ms-powerpoint": [ "ppt" ], 
  "application/font-woff": [ "woff" ], 
  "application/vnd.openxmlformats-officedocument.presentationml.template": [ "potx" ], 
  "text/plain": [ "txt", "text" ], 
  "application/x-tar": [ "tgz" ], 
  "application/vnd.openxmlformats-officedocument.spreadsheetml.template": [ "xltx" ], 
  "application/x-gzip": [ "gz" ], 
  "text/javascript": [ "js" ], 
  "text/html": [ "html", "htm" ], 
  "application/vnd.openxmlformats-officedocument.wordprocessingml.template": [ "dotx" ], 
  "image/x-icon": [ "ico" ], 
  "application/x-compressed-zip": [ "zip" ], 
  "application/vnd.openxmlformats-officedocument.presentationml.slideshow": [ "ppsx" ], 
  "text/css": [ "css" ], 
  "application/msword": [ "doc" ]
};

