#!/bin/sh

#update db
/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb4/arangod.pid --database.auto-upgrade true

rv=$?
. /usr/share/arangodb4/arangodb-helper
ar_exit_by_num $rv
