static string MR_server_server = 
  "################################################################################\n"
  "### @brief error handling\n"
  "###\n"
  "### @file\n"
  "###\n"
  "### DISCLAIMER\n"
  "###\n"
  "### Copyright 2012 triagens GmbH, Cologne, Germany\n"
  "###\n"
  "### Licensed under the Apache License, Version 2.0 (the \"License\");\n"
  "### you may not use this file except in compliance with the License.\n"
  "### You may obtain a copy of the License at\n"
  "###\n"
  "###     http://www.apache.org/licenses/LICENSE-2.0\n"
  "###\n"
  "### Unless required by applicable law or agreed to in writing, software\n"
  "### distributed under the License is distributed on an \"AS IS\" BASIS,\n"
  "### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
  "### See the License for the specific language governing permissions and\n"
  "### limitations under the License.\n"
  "###\n"
  "### Copyright holder is triAGENS GmbH, Cologne, Germany\n"
  "###\n"
  "### @author Dr. Frank Celler\n"
  "### @author Copyright 2012, triAGENS GmbH, Cologne, Germany\n"
  "################################################################################\n"
  "\n"
  "module Arango\n"
  "\n"
  "## -----------------------------------------------------------------------------\n"
  "## --SECTION--                                                     ArangoRequest\n"
  "## -----------------------------------------------------------------------------\n"
  "\n"
  "  class HttpRequest\n"
  "    def body()\n"
  "      return @body\n"
  "    end\n"
  "\n"
  "    def content_type()\n"
  "      return @content_type\n"
  "    end\n"
  "\n"
  "    def status()\n"
  "      return @status\n"
  "    end\n"
  "  end\n"
  "\n"
  "## -----------------------------------------------------------------------------\n"
  "## --SECTION--                                                    ArangoResponse\n"
  "## -----------------------------------------------------------------------------\n"
  "\n"
  "  class HttpResponse\n"
  "    def content_type()\n"
  "      return @content_type\n"
  "    end\n"
  "\n"
  "    def content_type=(type)\n"
  "      @content_type = type\n"
  "    end\n"
  "\n"
  "    def body()\n"
  "      return @body\n"
  "    end\n"
  "\n"
  "    def body=(text)\n"
  "      @body = text.to_s\n"
  "    end\n"
  "    def status()\n"
  "      return @status\n"
  "    end\n"
  "\n"
  "    def status=(code)\n"
  "      @status = code.to_i\n"
  "    end\n"
  "  end\n"
  "\n"
  "end\n"
  "\n"
  "################################################################################\n"
  "## --SECTION--                                                       END-OF-FILE\n"
  "################################################################################\n"
  "\n"
  "## Local Variables:\n"
  "## mode: outline-minor\n"
  "## outline-regexp: \"^\\\\(### @brief\\\\|## --SECTION--\\\\|# -\\\\*- \\\\)\"\n"
  "## End:\n"
;
