#!/bin/sh
test -d logs || mkdir logs

rspec --color --format d \
	api-compatibility-spec.rb \
	api-http-spec.rb \
	api-admin-spec.rb \
	api-aqlfunction-spec.rb \
	api-async-spec.rb \
	api-attributes-spec.rb \
	api-batch-spec.rb \
	api-collection-spec.rb \
	api-database-spec.rb \
	api-document-create-spec.rb \
	api-document-create-noncluster-spec.rb \
	api-document-delete-spec.rb \
	api-document-read-spec.rb \
	api-document-update-spec.rb \
	api-document-key-spec.rb \
	api-documents-spec.rb \
	api-edge-spec.rb \
	api-edge-noncluster-spec.rb \
	api-edges-spec.rb \
	api-graph-spec.rb \
	api-import-spec.rb \
	api-index-spec.rb \
	api-index-bitarray-spec.rb \
	api-index-hash-spec.rb \
	api-index-skiplist-spec.rb \
	api-explain-spec.rb \
	api-cursor-spec.rb \
	api-statistics-spec.rb \
        api-simple-all-spec.rb \
        api-simple-example-spec.rb \
        api-simple-fulltext-spec.rb \
        api-simple-geo-spec.rb \
        api-simple-range-spec.rb \
        api-simple-spec.rb \
        api-structures.rb \
	api-transactions-spec.rb \
	api-traversal-spec.rb \
        api-users-spec.rb 
