#!/usr/bin/env bash
set -u

# Make any failure in piped commands be reflected in the exit code.
set -o pipefail

readonly bash_source_dir="$(dirname $(readlink -f ${BASH_SOURCE[0]}))"


## locate executable
clang_format="${ARANGODB_CLANG_FORMAT:-""}"
clang_format_version="${ARANGODB_CLANG_FORMAT_VERSION:-"9.0.0"}"

# fallback if nothing is found
if [[ -z $clang_format ]]; then
    for candidate in "$HOME/.local/bin/clang-format" "clang-format-arangodb" "clang-format-9" "clang-format"; do
        echo "checking candidate $candidate"
        path="$(type -p ${candidate})"
        if [[ -n $path ]]; then
            clang_format="$path"
            echo "selecting this candidate"
            break;
        fi
    done
else
    echo "clang-format provided by environment"
fi

# fallback if nothing is found
if [[ -z $clang_format ]]; then
    echo "using fallback"
    clang_format="clang-format"
fi

## check version
echo "checking version of $clang_format"
version_string=$(${clang_format} --version)
re=".*version ${clang_format_version}.*"
if ! [[ $version_string =~ $re ]]; then
    echo "your version: '$version_string' does not match version 6.0.1"
    exit 1
fi


diff_target="HEAD"
if $TRAVIS; then
    # TODO - enable this once done
    # if ! $TRAVIS_PULL_REQUEST; then
    #     echo "NOT A PULL REQUEST"
    #     exit 0
    # fi
    diff_target="${TRAVIS_BRANCH}"
    echo "diffing against ${diff_target}"
fi

diff="$(git diff -U0 --no-color "${diff_target}" )"

if type colordiff 2>/dev/null; then
    #need pipefail option
    ${bash_source_dir}/lib/clang-format-diff.py --verbose -binary "${clang_format}" -style=file -p1 <<<"$diff" | colordiff -u3
else
    ${bash_source_dir}/lib/clang-format-diff.py --verbose -binary "${clang_format}" -style=file -p1 <<<"$diff"
fi

