static string JS_server_shell = 
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @brief JavaScript server functions\n"
  "///\n"
  "/// @file\n"
  "///\n"
  "/// DISCLAIMER\n"
  "///\n"
  "/// Copyright 2010-2011 triagens GmbH, Cologne, Germany\n"
  "///\n"
  "/// Licensed under the Apache License, Version 2.0 (the \"License\");\n"
  "/// you may not use this file except in compliance with the License.\n"
  "/// You may obtain a copy of the License at\n"
  "///\n"
  "///     http://www.apache.org/licenses/LICENSE-2.0\n"
  "///\n"
  "/// Unless required by applicable law or agreed to in writing, software\n"
  "/// distributed under the License is distributed on an \"AS IS\" BASIS,\n"
  "/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
  "/// See the License for the specific language governing permissions and\n"
  "/// limitations under the License.\n"
  "///\n"
  "/// Copyright holder is triAGENS GmbH, Cologne, Germany\n"
  "///\n"
  "/// @author Dr. Frank Celler\n"
  "/// @author Copyright 2011, triAGENS GmbH, Cologne, Germany\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "var internal = require(\"internal\");\n"
  "\n"
  "// -----------------------------------------------------------------------------\n"
  "// --SECTION--                                                             PRINT\n"
  "// -----------------------------------------------------------------------------\n"
  "\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @addtogroup V8Shell\n"
  "/// @{\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @brief global variable holding the current printed query\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "var it = undefined;\n"
  "\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @brief number of results to print\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "var queryLimit = 20;\n"
  "\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @brief prints a query\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "AvocadoFluentQuery.prototype.PRINT = function() {\n"
  "  if (this instanceof AvocadoFluentQuery) {\n"
  "    var count = 0;\n"
  "\n"
  "    try {\n"
  "      while (this.hasNext() && count++ < queryLimit) {\n"
  "        internal.output(JSON.stringify(this.next()), \"\\n\");\n"
  "      }\n"
  "\n"
  "      if (this.hasNext()) {\n"
  "        internal.output(\"...more results...\");\n"
  "      }\n"
  "\n"
  "      it = this;\n"
  "    }\n"
  "    catch (e) {\n"
  "      internal.output(\"encountered error while printing: \" + e);\n"
  "    }\n"
  "  }\n"
  "  else {\n"
  "    internal.output(this.toString());\n"
  "  }\n"
  "}\n"
  "\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @brief prints a query\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "AvocadoFluentQuery2.prototype.PRINT = function() {\n"
  "  if (this instanceof AvocadoFluentQuery2) {\n"
  "    var count = 0;\n"
  "\n"
  "    try {\n"
  "      while (this.hasNext() && count++ < queryLimit) {\n"
  "        internal.output(JSON.stringify(this.next()), \"\\n\");\n"
  "      }\n"
  "\n"
  "      if (this.hasNext()) {\n"
  "        internal.output(\"...more results...\");\n"
  "      }\n"
  "\n"
  "      it = this;\n"
  "    }\n"
  "    catch (e) {\n"
  "      internal.output(\"encountered error while printing: \" + e);\n"
  "    }\n"
  "  }\n"
  "  else {\n"
  "    internal.output(this.toString());\n"
  "  }\n"
  "}\n"
  "\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @brief prints a query\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "AvocadoCursor.prototype.PRINT = function() {\n"
  "  if (this instanceof AvocadoCursor) {\n"
  "    var count = 0;\n"
  "\n"
  "    try {\n"
  "      while (this.hasNext() && count++ < queryLimit) {\n"
  "        internal.output(JSON.stringify(this.next()), \"\\n\");\n"
  "      }\n"
  "\n"
  "      if (this.hasNext()) {\n"
  "        internal.output(\"...more results...\");\n"
  "      }\n"
  "\n"
  "      it = this;\n"
  "    }\n"
  "    catch (e) {\n"
  "      internal.output(\"encountered error while printing: \" + e);\n"
  "    }\n"
  "  }\n"
  "  else {\n"
  "    internal.output(this.toString());\n"
  "  }\n"
  "}\n"
  "\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "/// @}\n"
  "////////////////////////////////////////////////////////////////////////////////\n"
  "\n"
  "// Local Variables:\n"
  "// mode: outline-minor\n"
  "// outline-regexp: \"^\\\\(/// @brief\\\\|/// @addtogroup\\\\|// --SECTION--\\\\|/// @page\\\\|/// @}\\\\)\"\n"
  "// End:\n"
;
