#!/bin/sh
if command -v realpath > /dev/null; then
  true
else 
  realpath() {
    OURPWD=$PWD
    cd "$(dirname "$1")"
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
      cd "$(dirname "$LINK")"
      LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD"
    echo "$REALPATH"
  }
fi

me=$(realpath "$0")
program=$(basename "$me")
installation=$(dirname "$(dirname "$me")")
executable=$installation/usr/bin/$program
if [ -x "$executable" ] ; then
  exec "$executable" \
       --configuration none \
       --server.authentication true \
       --javascript.startup-directory "$installation/usr/share/arangodb3/js" \
       "$@"
fi
echo "Could not find executable ${executable}!"
exit 1
