# -*- mode: Makefile; -*-

## -----------------------------------------------------------------------------
## --SECTION--                                                           LIBRARY
## -----------------------------------------------------------------------------

################################################################################
### @brief library "libarangod.a"
################################################################################

arangod_libarangod_a_CPPFLAGS = \
	-I@top_srcdir@/arangod \
	$(AM_CPPFLAGS) 

arangod_libarangod_a_SOURCES = \
	arangod/Actions/actions.cpp \
	arangod/Actions/RestActionHandler.cpp \
	arangod/Ahuacatl/ahuacatl-access-optimiser.cpp \
	arangod/Ahuacatl/ahuacatl-ast-node.cpp \
	arangod/Ahuacatl/ahuacatl-bind-parameter.cpp \
	arangod/Ahuacatl/ahuacatl-codegen.cpp \
	arangod/Ahuacatl/ahuacatl-collections.cpp \
	arangod/Ahuacatl/ahuacatl-context.cpp \
	arangod/Ahuacatl/ahuacatl-conversions.cpp \
	arangod/Ahuacatl/ahuacatl-error.cpp \
	arangod/Ahuacatl/ahuacatl-explain.cpp \
	arangod/Ahuacatl/ahuacatl-functions.cpp \
	arangod/Ahuacatl/ahuacatl-grammar.cpp \
	arangod/Ahuacatl/ahuacatl-index.cpp \
	arangod/Ahuacatl/ahuacatl-node.cpp \
	arangod/Ahuacatl/ahuacatl-optimiser.cpp \
	arangod/Ahuacatl/ahuacatl-parser-functions.cpp \
	arangod/Ahuacatl/ahuacatl-parser.cpp \
	arangod/Ahuacatl/ahuacatl-result.cpp \
	arangod/Ahuacatl/ahuacatl-scope.cpp \
	arangod/Ahuacatl/ahuacatl-statement-dump.cpp \
	arangod/Ahuacatl/ahuacatl-statement-walker.cpp \
	arangod/Ahuacatl/ahuacatl-statementlist.cpp \
	arangod/Ahuacatl/ahuacatl-tokens.cpp \
	arangod/Ahuacatl/ahuacatl-variable.cpp \
	arangod/Aql/AqlItemBlock.cpp \
	arangod/Aql/AqlValue.cpp \
	arangod/Aql/Ast.cpp \
	arangod/Aql/AstNode.cpp \
	arangod/Aql/BindParameters.cpp \
	arangod/Aql/ExecutionBlock.cpp \
	arangod/Aql/ExecutionEngine.cpp \
	arangod/Aql/ExecutionNode.cpp \
	arangod/Aql/ExecutionPlan.cpp \
	arangod/Aql/ExecutionStats.cpp \
	arangod/Aql/Executor.cpp \
	arangod/Aql/Expression.cpp \
	arangod/Aql/Function.cpp \
	arangod/Aql/Functions.cpp \
	arangod/Aql/grammar.cpp \
	arangod/Aql/NodeFinder.cpp \
	arangod/Aql/Optimizer.cpp \
	arangod/Aql/OptimizerRules.cpp \
	arangod/Aql/Parser.cpp \
	arangod/Aql/Query.cpp \
	arangod/Aql/QueryRegistry.cpp \
	arangod/Aql/RangeInfo.cpp \
	arangod/Aql/RestAqlHandler.cpp \
	arangod/Aql/Scopes.cpp \
	arangod/Aql/Types.cpp \
	arangod/Aql/tokens.cpp \
	arangod/Aql/V8Expression.cpp \
	arangod/Aql/Variable.cpp \
	arangod/Aql/VariableGenerator.cpp \
	arangod/Aql/ModificationOptions.cpp \
	arangod/CapConstraint/cap-constraint.cpp \
	arangod/Cluster/AgencyComm.cpp \
	arangod/Cluster/ApplicationCluster.cpp \
	arangod/Cluster/ClusterComm.cpp \
	arangod/Cluster/ClusterInfo.cpp \
	arangod/Cluster/HeartbeatThread.cpp \
	arangod/Cluster/RestShardHandler.cpp \
	arangod/Cluster/ServerJob.cpp \
	arangod/Cluster/ServerState.cpp \
	arangod/Cluster/v8-cluster.cpp \
	arangod/Cluster/ClusterMethods.cpp \
	arangod/FulltextIndex/fulltext-handles.cpp \
	arangod/FulltextIndex/fulltext-index.cpp \
	arangod/FulltextIndex/fulltext-list.cpp \
	arangod/FulltextIndex/fulltext-query.cpp \
	arangod/FulltextIndex/fulltext-result.cpp \
	arangod/FulltextIndex/fulltext-wordlist.cpp \
	arangod/GeoIndex/GeoIndex.cpp \
	arangod/GeoIndex/geo-index.cpp \
	arangod/HashIndex/hash-array.cpp \
	arangod/HashIndex/hash-index.cpp \
	arangod/IndexOperators/index-operator.cpp \
	arangod/Replication/ContinuousSyncer.cpp \
	arangod/Replication/InitialSyncer.cpp \
	arangod/Replication/Syncer.cpp \
	arangod/RestHandler/RestBatchHandler.cpp \
	arangod/RestHandler/RestDocumentHandler.cpp \
	arangod/RestHandler/RestEdgeHandler.cpp \
	arangod/RestHandler/RestImportHandler.cpp \
	arangod/RestHandler/RestPleaseUpgradeHandler.cpp \
	arangod/RestHandler/RestReplicationHandler.cpp \
	arangod/RestHandler/RestUploadHandler.cpp \
	arangod/RestHandler/RestVocbaseBaseHandler.cpp \
	arangod/RestServer/ArangoServer.cpp \
	arangod/RestServer/ConsoleThread.cpp \
	arangod/RestServer/VocbaseContext.cpp \
	arangod/RestServer/arango.cpp \
	arangod/SkipLists/skiplistIndex.cpp \
	arangod/Utils/DocumentHelper.cpp \
	arangod/Utils/Exception.cpp \
	arangod/Utils/Transaction.cpp \
	arangod/V8Server/ApplicationV8.cpp \
	arangod/V8Server/V8DispatcherThread.cpp \
	arangod/V8Server/V8Job.cpp \
	arangod/V8Server/V8PeriodicTask.cpp \
	arangod/V8Server/V8QueueJob.cpp \
	arangod/V8Server/V8TimerTask.cpp \
	arangod/V8Server/v8-actions.cpp \
	arangod/V8Server/v8-dispatcher.cpp \
	arangod/V8Server/v8-query.cpp \
	arangod/V8Server/v8-vocbase.cpp \
	arangod/V8Server/v8-wrapshapedjson.cpp \
	arangod/V8Server/v8-vocindex.cpp \
	arangod/V8Server/v8-voccursor.cpp \
	arangod/V8Server/v8-replication.cpp \
	arangod/V8Server/v8-collection.cpp \
	arangod/V8Server/v8-collection-util.cpp \
	arangod/V8Server/v8-util.cpp \
	arangod/VocBase/auth.cpp \
	arangod/VocBase/barrier.cpp \
	arangod/VocBase/cleanup.cpp \
	arangod/VocBase/collection.cpp \
	arangod/VocBase/compactor.cpp \
	arangod/VocBase/datafile.cpp \
	arangod/VocBase/document-collection.cpp \
	arangod/VocBase/edge-collection.cpp \
	arangod/VocBase/general-cursor.cpp \
	arangod/VocBase/headers.cpp \
	arangod/VocBase/index.cpp \
	arangod/VocBase/key-generator.cpp \
	arangod/VocBase/primary-index.cpp \
	arangod/VocBase/replication-applier.cpp \
	arangod/VocBase/replication-common.cpp \
	arangod/VocBase/replication-dump.cpp \
	arangod/VocBase/replication-master.cpp \
	arangod/VocBase/server.cpp \
	arangod/VocBase/transaction.cpp \
	arangod/VocBase/voc-shaper.cpp \
	arangod/VocBase/vocbase.cpp \
	arangod/VocBase/vocbase-defaults.cpp \
	arangod/Wal/AllocatorThread.cpp \
	arangod/Wal/CollectorThread.cpp \
	arangod/Wal/LogfileManager.cpp \
	arangod/Wal/Logfile.cpp \
	arangod/Wal/Marker.cpp \
	arangod/Wal/RecoverState.cpp \
	arangod/Wal/RemoverThread.cpp \
	arangod/Wal/Slot.cpp \
	arangod/Wal/Slots.cpp \
	arangod/Wal/SynchroniserThread.cpp 

## -----------------------------------------------------------------------------
## --SECTION--                                                           PROGRAM
## -----------------------------------------------------------------------------

################################################################################
### @brief program "arangod"
################################################################################

bin_arangod_CPPFLAGS = \
	-I@top_srcdir@/arangod \
	$(AM_CPPFLAGS) 

bin_arangod_LDADD = \
	arangod/libarangod.a \
	lib/libarango_fe.a \
	lib/libarango_v8.a \
	lib/libarango.a \
	$(LIBS) \
	@V8_LIBS@ 

bin_arangod_SOURCES = \
	arangod/RestServer/arango.cpp

if ENABLE_MRUBY

bin_arangod_LDADD += \
	lib/libarango_mruby.a \
	@MRUBY_LIBS@

endif

################################################################################
## --SECTION--                                                  SCANNER & PARSER
################################################################################

################################################################################
### @brief flex
################################################################################

FLEXXX_FILES += \
	arangod/Ahuacatl/ahuacatl-tokens.cpp \
	arangod/Aql/tokens.cpp

################################################################################
### @brief bison
################################################################################

BISON_FILES += \
	arangod/Ahuacatl/ahuacatl-grammar.cpp \
	arangod/Aql/grammar.cpp

if ENABLE_MAINTAINER_MODE

CLEANUP += \
	arangod/Ahuacatl/ahuacatl-grammar.h \
	arangod/Ahuacatl/ahuacatl-grammar.cpp \
	arangod/Aql/grammar.h \
	arangod/Aql/grammar.cpp

endif

################################################################################
## --SECTION--                                                       END-OF-FILE
################################################################################

## Local Variables:
## mode: outline-minor
## outline-regexp: "^\\(### @brief\\|## --SECTION--\\|# -\\*- \\)"
## End:
