# -*- mode: Makefile; -*-

## -----------------------------------------------------------------------------
## --SECTION--                                                           LIBRARY
## -----------------------------------------------------------------------------

################################################################################
### @brief library "libarangod.a"
################################################################################

arangod_libarangod_a_CPPFLAGS = \
	-I@top_srcdir@/arangod \
	$(AM_CPPFLAGS) 

arangod_libarangod_a_SOURCES = \
	arangod/Actions/actions.cpp \
	arangod/Actions/RestActionHandler.cpp \
	arangod/Admin/ApplicationAdminServer.cpp \
	arangod/ApplicationServer/ApplicationFeature.cpp \
	arangod/ApplicationServer/ApplicationServer.cpp \
	arangod/Aql/AggregateBlock.cpp \
	arangod/Aql/AggregationOptions.cpp \
	arangod/Aql/AqlItemBlock.cpp \
	arangod/Aql/AqlItemBlockManager.cpp \
	arangod/Aql/AqlValue.cpp \
	arangod/Aql/Ast.cpp \
	arangod/Aql/AstNode.cpp \
	arangod/Aql/AttributeAccessor.cpp \
	arangod/Aql/BasicBlocks.cpp \
	arangod/Aql/BindParameters.cpp \
	arangod/Aql/CalculationBlock.cpp \
	arangod/Aql/Collection.cpp \
	arangod/Aql/CollectionScanner.cpp \
	arangod/Aql/ClusterBlocks.cpp \
	arangod/Aql/EnumerateCollectionBlock.cpp \
	arangod/Aql/EnumerateListBlock.cpp \
	arangod/Aql/ExecutionBlock.cpp \
	arangod/Aql/ExecutionEngine.cpp \
	arangod/Aql/ExecutionNode.cpp \
	arangod/Aql/ExecutionPlan.cpp \
	arangod/Aql/ExecutionStats.cpp \
	arangod/Aql/Executor.cpp \
	arangod/Aql/Expression.cpp \
	arangod/Aql/Function.cpp \
	arangod/Aql/Functions.cpp \
	arangod/Aql/grammar.cpp \
	arangod/Aql/IndexRangeBlock.cpp \
	arangod/Aql/ModificationBlock.cpp \
	arangod/Aql/NodeFinder.cpp \
	arangod/Aql/Optimizer.cpp \
	arangod/Aql/OptimizerRules.cpp \
	arangod/Aql/Parser.cpp \
	arangod/Aql/Query.cpp \
	arangod/Aql/QueryCache.cpp \
	arangod/Aql/QueryList.cpp \
	arangod/Aql/QueryRegistry.cpp \
	arangod/Aql/RangeInfo.cpp \
	arangod/Aql/Range.cpp \
	arangod/Aql/RestAqlHandler.cpp \
	arangod/Aql/Scopes.cpp \
	arangod/Aql/ShortStringStorage.cpp \
	arangod/Aql/SortBlock.cpp \
	arangod/Aql/SubqueryBlock.cpp \
	arangod/Aql/tokens.cpp \
	arangod/Aql/V8Expression.cpp \
	arangod/Aql/Variable.cpp \
	arangod/Aql/VariableGenerator.cpp \
	arangod/Aql/ModificationOptions.cpp \
	arangod/Cluster/AgencyComm.cpp \
	arangod/Cluster/ApplicationCluster.cpp \
	arangod/Cluster/ClusterComm.cpp \
	arangod/Cluster/ClusterInfo.cpp \
	arangod/Cluster/HeartbeatThread.cpp \
	arangod/Cluster/RestShardHandler.cpp \
	arangod/Cluster/ServerJob.cpp \
	arangod/Cluster/ServerState.cpp \
	arangod/Cluster/v8-cluster.cpp \
	arangod/Cluster/ClusterMethods.cpp \
	arangod/Dispatcher/ApplicationDispatcher.cpp \
	arangod/Dispatcher/Dispatcher.cpp \
	arangod/Dispatcher/DispatcherQueue.cpp \
	arangod/Dispatcher/DispatcherThread.cpp \
	arangod/Dispatcher/Job.cpp \
	arangod/Dispatcher/RequeueTask.cpp \
	arangod/FulltextIndex/fulltext-handles.cpp \
	arangod/FulltextIndex/fulltext-index.cpp \
	arangod/FulltextIndex/fulltext-list.cpp \
	arangod/FulltextIndex/fulltext-query.cpp \
	arangod/FulltextIndex/fulltext-result.cpp \
	arangod/FulltextIndex/fulltext-wordlist.cpp \
	arangod/GeoIndex/GeoIndex.cpp \
	arangod/HttpServer/ApplicationEndpointServer.cpp \
	arangod/HttpServer/AsyncJobManager.cpp \
	arangod/HttpServer/HttpCommTask.cpp \
	arangod/HttpServer/HttpHandler.cpp \
	arangod/HttpServer/HttpHandlerFactory.cpp \
	arangod/HttpServer/HttpListenTask.cpp \
	arangod/HttpServer/HttpServer.cpp \
	arangod/HttpServer/HttpServerJob.cpp \
	arangod/HttpServer/HttpsCommTask.cpp \
	arangod/HttpServer/HttpsServer.cpp \
	arangod/HttpServer/PathHandler.cpp \
	arangod/Indexes/CapConstraint.cpp \
	arangod/Indexes/EdgeIndex.cpp \
	arangod/Indexes/FulltextIndex.cpp \
	arangod/Indexes/GeoIndex2.cpp \
	arangod/Indexes/HashIndex.cpp \
	arangod/Indexes/Index.cpp \
	arangod/Indexes/PathBasedIndex.cpp \
	arangod/Indexes/PrimaryIndex.cpp \
	arangod/Indexes/SkiplistIndex2.cpp \
	arangod/Indexes/skiplist-helper.cpp \
	arangod/IndexOperators/index-operator.cpp \
	arangod/Replication/ContinuousSyncer.cpp \
	arangod/Replication/InitialSyncer.cpp \
	arangod/Replication/Syncer.cpp \
	arangod/Rest/AnyServer.cpp \
	arangod/RestHandler/RestAdminBaseHandler.cpp \
	arangod/RestHandler/RestAdminLogHandler.cpp \
	arangod/RestHandler/RestBaseHandler.cpp \
	arangod/RestHandler/RestBatchHandler.cpp \
	arangod/RestHandler/RestCursorHandler.cpp \
	arangod/RestHandler/RestDebugHelperHandler.cpp \
	arangod/RestHandler/RestDocumentHandler.cpp \
	arangod/RestHandler/RestEdgeHandler.cpp \
	arangod/RestHandler/RestExportHandler.cpp \
	arangod/RestHandler/RestImportHandler.cpp \
	arangod/RestHandler/RestJobHandler.cpp \
	arangod/RestHandler/RestPleaseUpgradeHandler.cpp \
	arangod/RestHandler/RestQueryCacheHandler.cpp \
	arangod/RestHandler/RestQueryHandler.cpp \
	arangod/RestHandler/RestReplicationHandler.cpp \
	arangod/RestHandler/RestShutdownHandler.cpp \
	arangod/RestHandler/RestSimpleHandler.cpp \
	arangod/RestHandler/RestSimpleQueryHandler.cpp \
	arangod/RestHandler/RestUploadHandler.cpp \
	arangod/RestHandler/RestVersionHandler.cpp \
	arangod/RestHandler/RestVocbaseBaseHandler.cpp \
	arangod/RestServer/ArangoServer.cpp \
	arangod/RestServer/ConsoleThread.cpp \
	arangod/RestServer/VocbaseContext.cpp \
	arangod/RestServer/arangod.cpp \
	arangod/Scheduler/ApplicationScheduler.cpp \
	arangod/Scheduler/ListenTask.cpp \
	arangod/Scheduler/PeriodicTask.cpp \
	arangod/Scheduler/Scheduler.cpp \
	arangod/Scheduler/SchedulerLibev.cpp \
	arangod/Scheduler/SchedulerThread.cpp \
	arangod/Scheduler/SignalTask.cpp \
	arangod/Scheduler/SocketTask.cpp \
	arangod/Scheduler/Task.cpp \
	arangod/Scheduler/TaskManager.cpp \
	arangod/Scheduler/TimerTask.cpp \
	arangod/Statistics/statistics.cpp \
	arangod/Utils/CollectionExport.cpp \
	arangod/Utils/Cursor.cpp \
	arangod/Utils/CursorRepository.cpp \
	arangod/Utils/DocumentHelper.cpp \
	arangod/Utils/StandaloneTransactionContext.cpp \
	arangod/Utils/Transaction.cpp \
	arangod/Utils/TransactionContext.cpp \
	arangod/Utils/V8TransactionContext.cpp \
	arangod/V8Server/ApplicationV8.cpp \
	arangod/V8Server/V8Job.cpp \
	arangod/V8Server/V8PeriodicTask.cpp \
	arangod/V8Server/V8QueueJob.cpp \
	arangod/V8Server/V8TimerTask.cpp \
	arangod/V8Server/V8Traverser.cpp \
	arangod/V8Server/v8-actions.cpp \
	arangod/V8Server/v8-collection.cpp \
	arangod/V8Server/v8-collection-util.cpp \
	arangod/V8Server/v8-dispatcher.cpp \
	arangod/V8Server/v8-query.cpp \
	arangod/V8Server/v8-replication.cpp \
	arangod/V8Server/v8-shape-conv.cpp \
	arangod/V8Server/v8-statistics.cpp \
	arangod/V8Server/v8-vocbase.cpp \
	arangod/V8Server/v8-vocindex.cpp \
	arangod/V8Server/v8-voccursor.cpp \
	arangod/V8Server/v8-user-structures.cpp \
	arangod/V8Server/v8-util.cpp \
	arangod/V8Server/v8-wrapshapedjson.cpp \
	arangod/VocBase/auth.cpp \
	arangod/VocBase/cleanup.cpp \
	arangod/VocBase/collection.cpp \
	arangod/VocBase/compactor.cpp \
	arangod/VocBase/datafile.cpp \
	arangod/VocBase/Ditch.cpp \
	arangod/VocBase/document-collection.cpp \
	arangod/VocBase/ExampleMatcher.cpp \
	arangod/VocBase/edge-collection.cpp \
	arangod/VocBase/headers.cpp \
	arangod/VocBase/KeyGenerator.cpp \
	arangod/VocBase/Legends.cpp \
	arangod/VocBase/replication-applier.cpp \
	arangod/VocBase/replication-common.cpp \
	arangod/VocBase/replication-dump.cpp \
	arangod/VocBase/replication-master.cpp \
	arangod/VocBase/server.cpp \
	arangod/VocBase/shape-accessor.cpp \
	arangod/VocBase/shaped-json.cpp \
	arangod/VocBase/Shaper.cpp \
	arangod/VocBase/transaction.cpp \
	arangod/VocBase/vocbase.cpp \
	arangod/VocBase/vocbase-defaults.cpp \
	arangod/VocBase/VocShaper.cpp \
	arangod/Wal/AllocatorThread.cpp \
	arangod/Wal/CollectorThread.cpp \
	arangod/Wal/LogfileManager.cpp \
	arangod/Wal/Logfile.cpp \
	arangod/Wal/Marker.cpp \
	arangod/Wal/RecoverState.cpp \
	arangod/Wal/RemoverThread.cpp \
	arangod/Wal/Slot.cpp \
	arangod/Wal/Slots.cpp \
	arangod/Wal/SynchroniserThread.cpp 

## -----------------------------------------------------------------------------
## --SECTION--                                                           PROGRAM
## -----------------------------------------------------------------------------

################################################################################
### @brief program "arangod"
################################################################################

bin_arangod_CPPFLAGS = \
	-I@top_srcdir@/arangod \
	$(AM_CPPFLAGS) 

bin_arangod_LDADD = \
	arangod/libarangod.a \
	lib/libarango_v8.a \
	lib/libarango.a \
	$(LIBS) \
	@V8_LIBS@ 

bin_arangod_SOURCES = \
	arangod/RestServer/arangod.cpp

################################################################################
## --SECTION--                                                  SCANNER & PARSER
################################################################################

################################################################################
### @brief flex
################################################################################

FLEXXX_FILES += \
	arangod/Aql/tokens.cpp

################################################################################
### @brief bison
################################################################################

BISON_FILES += \
	arangod/Aql/grammar.cpp

if ENABLE_MAINTAINER_MODE

CLEANUP += \
	arangod/Aql/grammar.h \
	arangod/Aql/grammar.cpp

endif

################################################################################
## --SECTION--                                                       END-OF-FILE
################################################################################

## Local Variables:
## mode: outline-minor
## outline-regexp: "^\\(### @brief\\|## --SECTION--\\|# -\\*- \\)"
## End:
