.TH arango-upgrade 8 "Fr 28. Sep 11:56:58 CEST 2012" "" "ArangoDB"
.SH NAME
arango-upgrade - upgrade script for the ArangoDB database server
.SH SYNOPSIS
arango-upgrade --database.directory database-directory
.SH DESCRIPTION
The arango-upgrade command can be used to perform any necessary system
data modification in an ArangoDB database after a version upgrade.
The command must be run with exclusive access to the server's data directory, 
that means the ArangoDB server must not be running and accessing the
datafiles in the specified data directory.

The arango-upgrade command will print a list of tasks it executes and a 
success/failure status for each. If some task cannot be accomplished
successfully, the root cause must be fixed and the arango-upgrade command be
run again afterwards.
.SH OPTIONS
The arango-upgrade binary the following option:

.IP "--database.directory <string>"
path to the database directory 
.SH EXAMPLES
.EX
shell> arango-upgrade --database.directory /data/arangodb
starts the upgrade script with database directory /data/arangodb 
.EE


.SH AUTHOR
	    Copyright 2012, triAGENS GmbH, Cologne, Germany
