.TH arango-password 8 "Fr 28. Sep 11:56:58 CEST 2012" "" "ArangoDB"
.SH NAME
arango-password - user setup utility for the ArangoDB database server
.SH SYNOPSIS
arango-password database-directory username [password]
.SH DESCRIPTION
The arango-password utility can be used to create additional users in an
ArangoDB database server.
The utility must be run with exclusive access to the server's data directory, 
meaning the ArangoDB server must not be running and accessing the
datafiles in the specified data directory.
.SH OPTIONS
The options of the arango-password utility are:
.IP "--database.directory <string>"
path to the database directory 
.IP "username" 
name of the user to add 
.IP "password"
password for the user. Leave empty for a password prompt 
.SH EXAMPLES
.EX
shell> arango-password --database.directory /data/arangodb fuchsia
creates a new user "fuchsia". Password prompt will follow 
.EE

.EX
shell> arango-password --database.directory /data/arangodb fuchsia "1234@ab"
creates a new user "fuchsia" with the specified password 
.EE


.SH AUTHOR
	    Copyright 2012, triAGENS GmbH, Cologne, Germany
