////////////////////////////////////////////////////////////////////////////////
/// @brief auto-generated file generated from errors.dat
////////////////////////////////////////////////////////////////////////////////

var internal = require("internal");

ModuleCache["/internal"].exports.errors = {
  "VOC_ERROR_ILLEGAL_STATE"      : { "code" : 1000, "message" : "illegal state" }, 
  "VOC_ERROR_SHAPER_FAILED"      : { "code" : 1001, "message" : "illegal shaper" }, 
  "VOC_ERROR_CORRUPTED_DATAFILE" : { "code" : 1002, "message" : "corrupted datafile" }, 
  "VOC_ERROR_MMAP_FAILED"        : { "code" : 1003, "message" : "mmap failed" }, 
  "VOC_ERROR_MSYNC_FAILED"       : { "code" : 1004, "message" : "msync failed" }, 
  "VOC_ERROR_NO_JOURNAL"         : { "code" : 1005, "message" : "no journal" }, 
  "VOC_ERROR_DATAFILE_SEALED"    : { "code" : 1006, "message" : "datafile sealed" }, 
  "VOC_ERROR_CORRUPTED_COLLECTION" : { "code" : 1007, "message" : "corrupted collection" }, 
  "VOC_ERROR_UNKNOWN_TYPE"       : { "code" : 1008, "message" : "unknown type" }, 
  "VOC_ERROR_ILLEGAL_PARAMETER"  : { "code" : 1009, "message" : "illegal parameter" }, 
  "VOC_ERROR_INDEX_EXISTS"       : { "code" : 1010, "message" : "index exists" }, 
  "VOC_ERROR_CONFLICT"           : { "code" : 1011, "message" : "conflict" }, 
  "VOC_ERROR_WRONG_PATH"         : { "code" : 1100, "message" : "wrong path" }, 
  "VOC_ERROR_CANNOT_RENAME"      : { "code" : 1101, "message" : "cannot rename" }, 
  "VOC_ERROR_WRITE_FAILED"       : { "code" : 1102, "message" : "write failed" }, 
  "VOC_ERROR_READ_ONLY"          : { "code" : 1103, "message" : "ready only" }, 
  "VOC_ERROR_DATAFILE_FULL"      : { "code" : 1104, "message" : "datafile full" }, 
  "VOC_ERROR_FILESYSTEM_FULL"    : { "code" : 1105, "message" : "filesystem full" }, 
  "VOC_ERROR_READ_FAILED"        : { "code" : 1106, "message" : "read failed" }, 
  "VOC_ERROR_FILE_NOT_FOUND"     : { "code" : 1107, "message" : "file not found" }, 
  "VOC_ERROR_FILE_NOT_ACCESSIBLE" : { "code" : 1108, "message" : "file not accessible" }, 
  "VOC_ERROR_DOCUMENT_NOT_FOUND" : { "code" : 1200, "message" : "document not found" }, 
  "ERROR_QUERY_OOM"              : { "code" : 1500, "message" : "out of memory" }, 
  "ERROR_QUERY_KILLED"           : { "code" : 1501, "message" : "query killed" }, 
  "ERROR_QUERY_PARSE"            : { "code" : 1510, "message" : "parse error: %s" }, 
  "ERROR_QUERY_EMPTY"            : { "code" : 1511, "message" : "query is empty" }, 
  "ERROR_QUERY_SPECIFICATION_INVALID" : { "code" : 1512, "message" : "query specification invalid" }, 
  "ERROR_QUERY_NUMBER_OUT_OF_RANGE" : { "code" : 1520, "message" : "number '%s' is out of range" }, 
  "ERROR_QUERY_LIMIT_VALUE_OUT_OF_RANGE" : { "code" : 1521, "message" : "limit value '%s' is out of range" }, 
  "ERROR_QUERY_TOO_MANY_JOINS"   : { "code" : 1540, "message" : "too many joins." }, 
  "ERROR_QUERY_COLLECTION_NAME_INVALID" : { "code" : 1550, "message" : "collection name '%s' is invalid" }, 
  "ERROR_QUERY_COLLECTION_ALIAS_INVALID" : { "code" : 1551, "message" : "collection alias '%s' is invalid" }, 
  "ERROR_QUERY_COLLECTION_ALIAS_REDECLARED" : { "code" : 1552, "message" : "collection alias '%s' is declared multiple times in the same query" }, 
  "ERROR_QUERY_COLLECTION_ALIAS_UNDECLARED" : { "code" : 1553, "message" : "collection alias '%s' is used but was not declared in the from clause" }, 
  "ERROR_QUERY_COLLECTION_NOT_FOUND" : { "code" : 1560, "message" : "unable to open collection '%s'" }, 
  "ERROR_QUERY_GEO_RESTRICTION_INVALID" : { "code" : 1570, "message" : "geo restriction for alias '%s' is invalid" }, 
  "ERROR_QUERY_GEO_INDEX_MISSING" : { "code" : 1571, "message" : "no suitable geo index found for geo restriction on '%s'" }, 
  "ERROR_QUERY_BIND_PARAMETER_MISSING" : { "code" : 1590, "message" : "no value specified for declared bind parameter '%s'" }, 
  "ERROR_QUERY_BIND_PARAMETER_REDECLARED" : { "code" : 1591, "message" : "value for bind parameter '%s' is declared multiple times" }, 
  "ERROR_QUERY_BIND_PARAMETER_UNDECLARED" : { "code" : 1592, "message" : "bind parameter '%s' was not declared in the query" }, 
  "ERROR_QUERY_BIND_PARAMETER_VALUE_INVALID" : { "code" : 1593, "message" : "invalid value for bind parameter '%s'" }, 
  "ERROR_QUERY_BIND_PARAMETER_NUMBER_OUT_OF_RANGE" : { "code" : 1594, "message" : "bind parameter number '%s' out of range" }, 
  "ERROR_CURSOR_NOT_FOUND"       : { "code" : 1600, "message" : "cursor not found" }, 
};

