version: 7.50.0.{build}

environment:
    matrix:
      - PRJ_GEN: "Visual Studio 11 2012 Win64"
        BDIR: msvc2012
        PRJ_CFG: Release
        OPENSSL: OFF
        TESTING: OFF
        STATICLIB: OFF
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
        PRJ_CFG: Release
        OPENSSL: OFF
        TESTING: OFF
        STATICLIB: OFF
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
        PRJ_CFG: Release
        OPENSSL: OFF
        TESTING: OFF
        STATICLIB: OFF
      - PRJ_GEN: "Visual Studio 11 2012 Win64"
        BDIR: msvc2012
        PRJ_CFG: Release
        OPENSSL: ON
        TESTING: OFF
        STATICLIB: OFF
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
        PRJ_CFG: Release
        OPENSSL: ON
        TESTING: OFF
        STATICLIB: OFF
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
        PRJ_CFG: Release
        OPENSSL: ON
        TESTING: OFF
        STATICLIB: OFF
      - PRJ_GEN: "Visual Studio 11 2012 Win64"
        BDIR: msvc2012
        PRJ_CFG: Release
        OPENSSL: OFF
        TESTING: ON
        STATICLIB: ON
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
        PRJ_CFG: Release
        OPENSSL: OFF
        TESTING: ON
        STATICLIB: ON
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
        PRJ_CFG: Release
        OPENSSL: OFF
        TESTING: ON
        STATICLIB: ON
      - PRJ_GEN: "Visual Studio 14 2015"
        BDIR: msvc2015
        PRJ_CFG: Release
        OPENSSL: OFF
        TESTING: ON
        STATICLIB: ON

build_script:
    - mkdir build.%BDIR%
    - cd build.%BDIR%
    - cmake .. -G"%PRJ_GEN%" -DCMAKE_USE_OPENSSL=%OPENSSL% -DCURL_STATICLIB=%STATICLIB% -DBUILD_TESTING=%TESTING% -DCURL_WERROR=ON
    - cmake --build . --config %PRJ_CFG% --clean-first

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
    only:
        - master
