name: cppcheck
on:
  pull_request:
    branches: [ devel, staging/replication-2.0 ]
    paths:
      - "arangod/**"
      - "client-tools/**"
      - "lib/**"
      - "tests/**"
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cppcheck
        run: |
          utils/cppcheck.sh
